version: '3.8'
services:
  db:
    container_name: mysql-marketplace
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"    
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    
  web:
    container_name: django-marketplace
    build: .
    image: sgalle16/django-marketplace-teis:latest
    restart: always
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             [ -f datadump.json ] && python manage.py loaddata datadump.json || echo 'No dump data found' &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./tienda_online:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

    nginx:
      image: nginx:latest
      container_name: nginx
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - /etc/letsencrypt:/etc/letsencrypt
        - /var/lib/letsencrypt:/var/lib/letsencrypt
      depends_on:
      - web

volumes:
  db:
