# Generated by Django 4.2.7 on 2024-03-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
    ]
